name: Docker Cloud Builds

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build for (development, staging, production)'
        required: true
        default: 'staging'
      push_images:
        description: 'Push images to registry (true, false)'
        required: true
        default: 'false'
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile*'
      - 'docker-compose*.yml'
      - 'package*.json'
      - '.github/workflows/docker-builds.yml'

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - component: app
            dockerfile: Dockerfile
            context: .
          - component: db-init
            dockerfile: Dockerfile.db-init
            context: .
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: ${{ github.event.inputs.push_images == 'true' || github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.component }}
          tags: |
            type=raw,value=${{ github.event.inputs.environment || 'latest' }}

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event.inputs.push_images == 'true' || github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max